name: Publish Python SKT distributions to TestPyPI

on:
  push:
    branches:
      - master
    paths:
      - 'setup.py'

jobs:
  build-n-publish:
    name: Build and publish Python SKT distributions to PyPI and TestPyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install setuptools
      run: >-
        python -m
        pip install
        setuptools
        wheel
        --user
    - run: pip install --upgrade pip
    - name: Build a binary wheel and a source tarball
      run: >-
        python
        setup.py
        sdist
        bdist_wheel
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
